# TMBD DATASET

## Importing Data

In [1]:
# Import the relevant modules
import json
import requests
import pandas as pd
import time
import itertools
import os
import numpy as np
import random
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pickle
import datetime
from tqdm import tqdm

In [2]:
cwd = os.getcwd()
print(cwd)

/Users/zora/Desktop/springboard/Captone_TMDB/TMBD_API/Top10000

In [3]:
files = os.listdir() 
print(files)

['Credit_Top10000.ipynb', 'Movie_Top10000.ipynb', '.DS_Store', 'Credit_Top10000-Copy1.ipynb', 'Discover_Top10000.csv', 'Discover_Top10000.ipynb', 'TMDB_Top10000_discover.ipynb', '.ipynb_checkpoints', 'popularity_Top10000.csv']

In [4]:
df = pd.read_csv('Discover_Top10000.csv')
df.head()

,page,total_results,total_pages,popularity,vote_count,video,poster_path,id,adult,backdrop_path,original_language,original_title,genre_ids,title,vote_average,overview,release_date
0,1,10000,500,407.572,3655,False,/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg,419704,False,/5BwqwxMEjeFtdknRV792Svo0K1v.jpg,en,Ad Astra,"[18, 878]",Ad Astra,6.0,"The near future, a time when both hope and har...",2019-09-17
1,1,10000,500,156.971,56,False,/ygCQnDEqUEIamBpdQdDYnFfxvgM.jpg,339095,False,/t93doi7EzoqLFckidrGGnukFPwd.jpg,en,The Last Days of American Crime,"[28, 80, 53]",The Last Days of American Crime,5.4,"In the not-too-distant future, where as a fina...",2020-06-05
2,1,10000,500,153.391,4479,False,/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg,454626,False,/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg,en,Sonic the Hedgehog,"[28, 35, 878, 10751]",Sonic the Hedgehog,7.5,Based on the global blockbuster videogame fran...,2020-02-12
3,1,10000,500,149.957,38,False,/avl9MEQhtvokNnzoWepkmHBZ2ss.jpg,574982,False,/6F66CSqvVAVZHeNMRUNX6E7qPE6.jpg,ru,Аванпост,"[28, 878, 53]",The Blackout,6.2,Contact between most towns on Earth has been s...,2019-11-21
4,1,10000,500,144.917,7818,False,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,496243,False,/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg,ko,기생충,"[35, 18, 53]",Parasite,8.5,"All unemployed, Ki-taek's family takes peculia...",2019-05-30

In [5]:
IDs = list(df['id'])

In [6]:
api_key = '3a99c05a3715265405738606e37342c2'
def get_movie_id(IDs):
    
    df_all = pd.DataFrame()
    
    for i in tqdm(IDs):
        
        url = 'https://api.themoviedb.org/3/movie/'+ format(i) + '?api_key='+ api_key
        r = requests.get(url)
        json_data = r.json()
        df_movie = pd.DataFrame.from_dict(json_data, orient='index').T
        df_all = df_all.append(df_movie, ignore_index=True)
        time.sleep(0.01)
    
    return df_all

if __name__ == '__main__':
    
    df_movie = get_movie_id(IDs)

100%|██████████| 10000/10000 [38:59<00:00,  4.28it/s]

In [7]:
df_movie.head()

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,status_code,status_message
0,False,/5BwqwxMEjeFtdknRV792Svo0K1v.jpg,None,87500000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.foxmovies.com/movies/ad-astra,419704,tt2935510,en,Ad Astra,...,123,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The answers we seek are just outside our reach,Ad Astra,False,6,3658,NaN,NaN
1,False,/t93doi7EzoqLFckidrGGnukFPwd.jpg,None,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",https://www.netflix.com/title/80198975,339095,tt1552211,en,The Last Days of American Crime,...,148,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,The Last Days of American Crime,False,5.3,61,NaN,NaN
2,False,/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg,None,85000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",https://www.paramountmovies.com/movies/sonic-t...,454626,tt3794354,en,Sonic the Hedgehog,...,99,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Whole New Speed of Hero,Sonic the Hedgehog,False,7.5,4487,NaN,NaN
3,False,/6F66CSqvVAVZHeNMRUNX6E7qPE6.jpg,None,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 878, '...",,574982,tt8664988,ru,Аванпост,...,127,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,Who's going to save you when the world falls i...,The Blackout,False,6,40,NaN,NaN
4,False,/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg,None,11363000,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",https://www.parasite-movie.com/,496243,tt6751668,ko,기생충,...,133,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Act like you own the place.,Parasite,False,8.5,7831,NaN,NaN

In [8]:
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  9999 non-null   object
 1   backdrop_path          9495 non-null   object
 2   belongs_to_collection  2378 non-null   object
 3   budget                 9999 non-null   object
 4   genres                 9999 non-null   object
 5   homepage               9957 non-null   object
 6   id                     9999 non-null   object
 7   imdb_id                9947 non-null   object
 8   original_language      9999 non-null   object
 9   original_title         9999 non-null   object
 10  overview               9999 non-null   object
 11  popularity             9999 non-null   object
 12  poster_path            9955 non-null   object
 13  production_companies   9999 non-null   object
 14  production_countries   9999 non-null   object
 15  release_date           9999 non-null   object
 16  revenue                9999 non-null   object
 17  runtime                9987 non-null   object
 18  spoken_languages       9999 non-null   object
 19  status                 9999 non-null   object
 20  tagline                9999 non-null   object
 21  title                  9999 non-null   object
 22  video                  9999 non-null   object
 23  vote_average           9999 non-null   object
 24  vote_count             9999 non-null   object
 25  status_code            1 non-null      object
 26  status_message         1 non-null      object
dtypes: object(27)
memory usage: 2.1+ MB

In [9]:
df_movie.shape

(10000, 27)

In [10]:
df = df_movie.drop(['status_code','status_message'], axis =1)
df.head()

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/5BwqwxMEjeFtdknRV792Svo0K1v.jpg,None,87500000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.foxmovies.com/movies/ad-astra,419704,tt2935510,en,Ad Astra,...,2019-09-17,132807427,123,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The answers we seek are just outside our reach,Ad Astra,False,6,3658
1,False,/t93doi7EzoqLFckidrGGnukFPwd.jpg,None,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",https://www.netflix.com/title/80198975,339095,tt1552211,en,The Last Days of American Crime,...,2020-06-05,0,148,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,The Last Days of American Crime,False,5.3,61
2,False,/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg,None,85000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",https://www.paramountmovies.com/movies/sonic-t...,454626,tt3794354,en,Sonic the Hedgehog,...,2020-02-12,306766470,99,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Whole New Speed of Hero,Sonic the Hedgehog,False,7.5,4487
3,False,/6F66CSqvVAVZHeNMRUNX6E7qPE6.jpg,None,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 878, '...",,574982,tt8664988,ru,Аванпост,...,2019-11-21,2746207,127,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,Who's going to save you when the world falls i...,The Blackout,False,6,40
4,False,/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg,None,11363000,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",https://www.parasite-movie.com/,496243,tt6751668,ko,기생충,...,2019-05-30,245924070,133,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Act like you own the place.,Parasite,False,8.5,7831

In [11]:
df.describe()

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
count,9999,9495,2378,9999,9999,9957,9999,9947,9999,9999,...,9999,9999,9987,9999,9999,9999,9999,9999,9999.0,9999
unique,1,9495,1032,719,2175,3641,9999,9939,46,9751,...,5948,5548,220,985,4,7584,9702,1,70.0,2842
top,False,/srUFbOIURwXCWejMHasXyhMb3xO.jpg,"{'id': 693368, 'name': 'Scooby Doo Animated Co...",0,"[{'id': 18, 'name': 'Drama'}]",,7182,,en,Dracula,...,2020-06-10,0,90,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,,Dracula,False,6.0,0
freq,9999,1,26,4245,590,6267,1,9,8368,4,...,23,4257,372,6133,9912,2373,4,9999,429.0,147

In [12]:
df.to_csv('Movie_Top10000.csv', index = False)